# Generated by Django 2.2 on 2021-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211102_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_picture/default/profilepic.png', upload_to='profile_picture'),
        ),
    ]
